xiaomei_xiaomei_homepage:
    path:     /hello/{name}
    defaults: { _controller: XiaomeiXiaomeiBundle:Default:index :name='default'}

xiaomei_xiaomei_home:
    path:     /
    defaults: { _controller: XiaomeiXiaomeiBundle:Default:home }

xiaomei_xiaomei_legal:
    path:     /legal/
    defaults: { _controller: XiaomeiXiaomeiBundle:Default:legal }

xiaomei_xiaomei_order:
    path:     /order/
    defaults: { _controller: XiaomeiXiaomeiBundle:Cours:ordersubmit }


xiaomei_xiaomei_about:
    path:     /a-propos/
    defaults: { _controller: XiaomeiXiaomeiBundle:Default:about }

xiaomei_xiaomei_showcoursall:
    path:     /showcours/{tri}
    defaults: { _controller: XiaomeiXiaomeiBundle:Cours:showcours,tri:'c.dateCours'}

xiaomei_xiaomei_showtri:
    path:     /showtri/
    defaults: { _controller: XiaomeiXiaomeiBundle:Cours:showtri }

xiaomei_xiaomei_showcour:
    path:     /cours/{id}
    defaults: { _controller: XiaomeiXiaomeiBundle:Cours:showcour }

xiaomei_xiaomei_delete:
    path:     /moncompte/deletecontenu/{id}/
    defaults: { _controller: XiaomeiXiaomeiBundle:Cours:deletecontenu }

xiaomei_xiaomei_moncompte:
    path:     /moncompte/
    defaults: { _controller: XiaomeiXiaomeiBundle:User:moncompte }

xiaomei_xiaomei_modifierprofil:
    path:     /moncompte/modifierprofil/
    defaults: { _controller: XiaomeiXiaomeiBundle:User:modifierprofil }

xiaomei_xiaomei_mesformations:
    path:     /moncompte/mesformations/
    defaults: { _controller: XiaomeiXiaomeiBundle:User:mesformations }

xiaomei_xiaomei_mesinscriptions:
    path:     /moncompte/mesinscriptions/
    defaults: { _controller: XiaomeiXiaomeiBundle:User:mesinscriptions }

xiaomei_xiaomei_cancelinscriptions:
    path:     /moncompte/cancelinscriptions/{id}
    defaults: { _controller: XiaomeiXiaomeiBundle:Cours:cancelinscriptions }


xiaomei_xiaomei_create_cours:
    path:     /moncompte/createcours/
    defaults: { _controller: XiaomeiXiaomeiBundle:Cours:createcours }

xiaomei_xiaomei_cancelcours:
    path:     /moncompte/cancelcours/{id}
    defaults: { _controller: XiaomeiXiaomeiBundle:Cours:cancelcours }
xiaomei_xiaomei_formateur:
    path:     /formateur/{id}
    defaults: { _controller: XiaomeiXiaomeiBundle:User:formateur }


#user
xiaomei_xiaomei_register:
    path:     /inscription/
    defaults: { _controller: XiaomeiXiaomeiBundle:User:register }

xiaomei_xiaomei_inscriptioncours:
    path:     /inscriptioncours/{id}
    defaults: { _controller: XiaomeiXiaomeiBundle:Cours:registercours }

xiaomei_xiaomei_inscriptioncoursconfirmer:
    path:     /inscriptioncoursconfirmer/{id}
    defaults: { _controller: XiaomeiXiaomeiBundle:Cours:registercoursconfirmer }


