parameters:
#    xiaomei_xiaomei.example.class: Xiaomei\XiaomeiBundle\Example

services:
#    xiaomei_xiaomei.example:
#        class: %xiaomei_xiaomei.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
