<?php

namespace Proxies\__CG__\Xiaomei\XiaomeiBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Cours extends \Xiaomei\XiaomeiBundle\Entity\Cours implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Xiaomei\\XiaomeiBundle\\Entity\\Cours' . "\0" . 'id', '' . "\0" . 'Xiaomei\\XiaomeiBundle\\Entity\\Cours' . "\0" . 'name', '' . "\0" . 'Xiaomei\\XiaomeiBundle\\Entity\\Cours' . "\0" . 'image', '' . "\0" . 'Xiaomei\\XiaomeiBundle\\Entity\\Cours' . "\0" . 'dateCours', '' . "\0" . 'Xiaomei\\XiaomeiBundle\\Entity\\Cours' . "\0" . 'lieu', '' . "\0" . 'Xiaomei\\XiaomeiBundle\\Entity\\Cours' . "\0" . 'duration', '' . "\0" . 'Xiaomei\\XiaomeiBundle\\Entity\\Cours' . "\0" . 'descriptif', '' . "\0" . 'Xiaomei\\XiaomeiBundle\\Entity\\Cours' . "\0" . 'nrPlaceTotal', '' . "\0" . 'Xiaomei\\XiaomeiBundle\\Entity\\Cours' . "\0" . 'nrPlaceRestant', '' . "\0" . 'Xiaomei\\XiaomeiBundle\\Entity\\Cours' . "\0" . 'dateCreated', '' . "\0" . 'Xiaomei\\XiaomeiBundle\\Entity\\Cours' . "\0" . 'isannulation', '' . "\0" . 'Xiaomei\\XiaomeiBundle\\Entity\\Cours' . "\0" . 'dateCancellation', '' . "\0" . 'Xiaomei\\XiaomeiBundle\\Entity\\Cours' . "\0" . 'category', '' . "\0" . 'Xiaomei\\XiaomeiBundle\\Entity\\Cours' . "\0" . 'user', '' . "\0" . 'Xiaomei\\XiaomeiBundle\\Entity\\Cours' . "\0" . 'inscription', '' . "\0" . 'Xiaomei\\XiaomeiBundle\\Entity\\Cours' . "\0" . 'countInscrit', '' . "\0" . 'Xiaomei\\XiaomeiBundle\\Entity\\Cours' . "\0" . 'inscritannule');
        }

        return array('__isInitialized__', '' . "\0" . 'Xiaomei\\XiaomeiBundle\\Entity\\Cours' . "\0" . 'id', '' . "\0" . 'Xiaomei\\XiaomeiBundle\\Entity\\Cours' . "\0" . 'name', '' . "\0" . 'Xiaomei\\XiaomeiBundle\\Entity\\Cours' . "\0" . 'image', '' . "\0" . 'Xiaomei\\XiaomeiBundle\\Entity\\Cours' . "\0" . 'dateCours', '' . "\0" . 'Xiaomei\\XiaomeiBundle\\Entity\\Cours' . "\0" . 'lieu', '' . "\0" . 'Xiaomei\\XiaomeiBundle\\Entity\\Cours' . "\0" . 'duration', '' . "\0" . 'Xiaomei\\XiaomeiBundle\\Entity\\Cours' . "\0" . 'descriptif', '' . "\0" . 'Xiaomei\\XiaomeiBundle\\Entity\\Cours' . "\0" . 'nrPlaceTotal', '' . "\0" . 'Xiaomei\\XiaomeiBundle\\Entity\\Cours' . "\0" . 'nrPlaceRestant', '' . "\0" . 'Xiaomei\\XiaomeiBundle\\Entity\\Cours' . "\0" . 'dateCreated', '' . "\0" . 'Xiaomei\\XiaomeiBundle\\Entity\\Cours' . "\0" . 'isannulation', '' . "\0" . 'Xiaomei\\XiaomeiBundle\\Entity\\Cours' . "\0" . 'dateCancellation', '' . "\0" . 'Xiaomei\\XiaomeiBundle\\Entity\\Cours' . "\0" . 'category', '' . "\0" . 'Xiaomei\\XiaomeiBundle\\Entity\\Cours' . "\0" . 'user', '' . "\0" . 'Xiaomei\\XiaomeiBundle\\Entity\\Cours' . "\0" . 'inscription', '' . "\0" . 'Xiaomei\\XiaomeiBundle\\Entity\\Cours' . "\0" . 'countInscrit', '' . "\0" . 'Xiaomei\\XiaomeiBundle\\Entity\\Cours' . "\0" . 'inscritannule');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Cours $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getCountInscrit()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCountInscrit', array());

        return parent::getCountInscrit();
    }

    /**
     * {@inheritDoc}
     */
    public function setCountInscrit($countInscrit)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCountInscrit', array($countInscrit));

        return parent::setCountInscrit($countInscrit);
    }

    /**
     * {@inheritDoc}
     */
    public function getInscritannule()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInscritannule', array());

        return parent::getInscritannule();
    }

    /**
     * {@inheritDoc}
     */
    public function setInscritannule($inscritannule)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInscritannule', array($inscritannule));

        return parent::setInscritannule($inscritannule);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', array($name));

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', array());

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setImage($image)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImage', array($image));

        return parent::setImage($image);
    }

    /**
     * {@inheritDoc}
     */
    public function getImage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImage', array());

        return parent::getImage();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateCours($dateCours)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateCours', array($dateCours));

        return parent::setDateCours($dateCours);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateCours()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateCours', array());

        return parent::getDateCours();
    }

    /**
     * {@inheritDoc}
     */
    public function setLieu($lieu)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLieu', array($lieu));

        return parent::setLieu($lieu);
    }

    /**
     * {@inheritDoc}
     */
    public function getLieu()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLieu', array());

        return parent::getLieu();
    }

    /**
     * {@inheritDoc}
     */
    public function setDuration($duration)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDuration', array($duration));

        return parent::setDuration($duration);
    }

    /**
     * {@inheritDoc}
     */
    public function getDuration()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDuration', array());

        return parent::getDuration();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescriptif($descriptif)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescriptif', array($descriptif));

        return parent::setDescriptif($descriptif);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescriptif()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescriptif', array());

        return parent::getDescriptif();
    }

    /**
     * {@inheritDoc}
     */
    public function setNrPlaceTotal($nrPlaceTotal)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNrPlaceTotal', array($nrPlaceTotal));

        return parent::setNrPlaceTotal($nrPlaceTotal);
    }

    /**
     * {@inheritDoc}
     */
    public function getNrPlaceTotal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNrPlaceTotal', array());

        return parent::getNrPlaceTotal();
    }

    /**
     * {@inheritDoc}
     */
    public function setNrPlaceRestant($nrPlaceRestant)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNrPlaceRestant', array($nrPlaceRestant));

        return parent::setNrPlaceRestant($nrPlaceRestant);
    }

    /**
     * {@inheritDoc}
     */
    public function getNrPlaceRestant()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNrPlaceRestant', array());

        return parent::getNrPlaceRestant();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateCreated($dateCreated)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateCreated', array($dateCreated));

        return parent::setDateCreated($dateCreated);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateCreated()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateCreated', array());

        return parent::getDateCreated();
    }

    /**
     * {@inheritDoc}
     */
    public function setCategory(\Xiaomei\XiaomeiBundle\Entity\Category $category = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCategory', array($category));

        return parent::setCategory($category);
    }

    /**
     * {@inheritDoc}
     */
    public function getCategory()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCategory', array());

        return parent::getCategory();
    }

    /**
     * {@inheritDoc}
     */
    public function setUser(\Xiaomei\XiaomeiBundle\Entity\User $user = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUser', array($user));

        return parent::setUser($user);
    }

    /**
     * {@inheritDoc}
     */
    public function getUser()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUser', array());

        return parent::getUser();
    }

    /**
     * {@inheritDoc}
     */
    public function addInscription(\Xiaomei\XiaomeiBundle\Entity\Inscription $inscription)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addInscription', array($inscription));

        return parent::addInscription($inscription);
    }

    /**
     * {@inheritDoc}
     */
    public function removeInscription(\Xiaomei\XiaomeiBundle\Entity\Inscription $inscription)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeInscription', array($inscription));

        return parent::removeInscription($inscription);
    }

    /**
     * {@inheritDoc}
     */
    public function getInscription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInscription', array());

        return parent::getInscription();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateCancellation($dateCancellation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateCancellation', array($dateCancellation));

        return parent::setDateCancellation($dateCancellation);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateCancellation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateCancellation', array());

        return parent::getDateCancellation();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsannulation($isannulation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsannulation', array($isannulation));

        return parent::setIsannulation($isannulation);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsannulation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsannulation', array());

        return parent::getIsannulation();
    }

}
