<?php

namespace Xiaomei\XiaomeiBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
	public function findFullSingleContent($id){

		$query = $this->createQueryBuilder('u')
				->select('u,i,c')	//hyper facile à oublier
				 ->where('u.id = :id') 
				 ->leftJoin('u.inscription', 'i')	
			    ->leftJoin('u.cours', 'c')					   
			    ->setParameter(':id', $id)
			    ->getQuery();

		$content = $query->getSingleResult();

		return $content;
//comment faire jointure many to many ; User et cours, pour avoir liste des cours dispensé et liste de cours suivi

		

	}

}
