security:
    firewalls:
        secured_area:
            pattern:    ^/
            anonymous: ~
            form_login:
                login_path:  /connexion/
                check_path:  /login_check
            logout:
                path:   /logout
                target: /
            remember_me:
                key:      "%secret%"
                lifetime: 31536000 # 365 days in seconds
                path:     /
                domain:   ~ # Defaults to the current domain from $_SERVER

    access_control:
        - { path: ^/moncompte/, roles: ROLE_USER }

    providers:
        users:
            entity: { class: Xiaomei\XiaomeiBundle\Entity\User, property: username }

    encoders:
        Xiaomei\XiaomeiBundle\Entity\User:
            algorithm: sha512

    #être admin donne tous les droits qu'ont les user
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER